name: CI/CD

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js (example for a Node.js project)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the project
      run: npm run build

    - name: Deploy (example for static sites)
      if: github.ref == 'refs/heads/master'
      run: echo "Deployment process..."
      # Add deployment steps here, e.g., upload to AWS S3, Azure, Firebase, etc.
